### ISSUE TITLE
TODO #1

### ISSUE THREAD

**Issue by GMart** [GMart/RSVoiP-CS374#1]
We can use this Issue tracker to keep track of what we have to add the the program. It even supports task lists!
- [x] Get a GUI working
- [x] Get sockets working within the program in the master branch
- [x] Get audio system working
- [ ] Make sure we can get data to go between networks and NATs.

Thanks!

**Comment by BanishedAngel** [comment]
UPDATE: The GUI is working and the sockets work fine when communicating on the host machine. Communication over the internet and audio transfer are yet to be implemented.
